---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - mkdir roles



install:
  # Install Ansible.
  - pip install ansible
  - printf '[defaults]\nroles_path = ../' > ansible.cfg

  # Add ansible.cfg to pick up roles path.
  #- "printf '[defaults]\nroles_path = ../' > ansible.cfg"


script:
  # We'll add some commands to test the role here.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check