---
- name: check we_username variable
  fail: msg="Variable '{{ we_username }}' is not defined" 
  when: we_username is not defined
  tags: check

- name: check we_working_root_dir variable
  fail: msg="Variable '{{ we_working_root_dir }}' is not defined" 
  when: we_working_root_dir is not defined
  tags: check

