---
- name: Create group "{{ we_group }}"
  group: name="{{ we_group }}" state=present

- name: Create user "{{we_username}}"
  user: name="{{we_username}}" state=present group="{{ we_group}}"

- name: create working directories
  file: dest="{{ we_working_root_dir }}/{{ item }}" state=directory mode=0775 group="{{ we_group }}"
  with_items: 
    - etc
    - jar
    - log
    - opt
    - www
    - ansible

- name: change users umask
  lineinfile: dest="{{ we_userhome }}/.profile" regexp=^umask\\s+\\d+ line='umask {{ we_umask }}'
