---
- name: Create group {{ we_username }}
  group: name=oscaro state=present

- name: Create user "{{we_username}}"
  user: name="{{we_username}}" state=present

- name: Add user in groups
  user: name="{{we_username}}" state=present groups="{{we_usergroups}}"
  when: we_usergroups != false

- name: create working directories
  file: dest="{{ we_working_root_dir }}/{{ item }}" state=directory mode=0775  owner="{{ we_username }}" group="{{ we_username }}"
  with_items: 
    - etc
    - jar
    - log
    - opt
    - www

- name: change users umask
  lineinfile: dest=/home/{{ we_username }}/.profile regexp=^umask\\s+\\d+ line='umask 0002'
